### ISSUE TITLE
Can't start docker image

### ISSUE THREAD

**Issue by bzg** [Parisson/DevBox#1]
Hi,

thanks for sharing DevBox!

After cloning the repo and launching `install.sh` from `Ubuntu (Linux bzg 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 i686 GNU/Linux)` and docker v. 1.12.6, get this error:

```
Starting devbox_home_1
Starting devbox_lib_1
Starting devbox_log_1
Starting devbox_rabbitmq_1
Starting devbox_static_1
Starting devbox_search_1
Starting devbox_db_1
Starting devbox_worker_1
Starting devbox_app_1
Starting devbox_nginx_1

ERROR: for nginx  Cannot start service nginx: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/home/guerry/DevBox/Telemeta/examples/deploy/nginx-app.conf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/6d309282029e8ecbcc803deeebbe61c13af6da53ea8d4cdac79017aab093990a\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/6d309282029e8ecbcc803deeebbe61c13af6da53ea8d4cdac79017aab093990a/etc/nginx/conf.d/default.conf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.
```
... which is a bit cryptic to me, can you help me debugging this?

Thanks!

**Comment by thomasfillon** [comment]
Hi Bastien,

I'm sorry but this repository is obsolete. Its purpose was to facilitate Telemeta setup for development.
Everything is now integrated into [Telemeta repository](https://github.com/Parisson/Telemeta). So you should give it a try ;)
Thanks for the feedback !

**Comment by bzg** [comment]
Hi Thomas,

thanks for replying, I'll give it a try and get back to you!

All best,

**Comment by thomasfillon** [comment]
Ok fine thank you !
